# Generated by Django 5.2.8 on 2026-02-08 10:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalauditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portalauditlog',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='portalmediaasset',
            name='file',
            field=models.FileField(upload_to='portal/media/', validators=[core.validators.validate_upload_extension, core.validators.validate_upload_file_size]),
        ),
    ]
