# Generated by Django 5.2.8 on 2026-03-26 06:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_portalauditlog_target_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalmediaasset',
            name='file',
            field=models.FileField(max_length=255, upload_to='portal/media/', validators=[core.validators.validate_upload_extension, core.validators.validate_upload_file_size]),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='og_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='portal/og/'),
        ),
    ]
