# Generated by Django 5.2.8 on 2026-03-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived news are hidden from public views'),
        ),
    ]
