# Generated by Django 5.2.8 on 2026-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_slug_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='news/thumbnails/'),
        ),
    ]
