# Generated by Django 5.2.8 on 2026-04-09 03:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_document',
            field=models.FileField(blank=True, help_text='File Word gốc của bài viết để lưu trữ và truy xuất sau này.', max_length=255, null=True, upload_to='news/source-documents/', validators=[core.validators.validate_upload_extension, core.validators.validate_upload_file_size]),
        ),
    ]
