# Generated by Django 5.2.8 on 2025-12-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(help_text="URL path or Django URL name (e.g. '/about/' or 'core:home')", max_length=200)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome class (e.g. 'fas fa-home')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('header', 'Header/Navbar'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], default='header', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
