# Generated by Django 5.2.8 on 2025-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hệ đào tạo')),
                ('short_name', models.CharField(max_length=100, verbose_name='Tên ngắn')),
                ('tagline', models.CharField(max_length=300, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('partner_description', models.TextField(verbose_name='Giới thiệu đối tác')),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='training_programs/partners/', verbose_name='Logo đối tác')),
                ('highlights', models.TextField(help_text='Mỗi dòng là một điểm nổi bật', verbose_name='Điểm nổi bật')),
                ('curriculum', models.TextField(blank=True, verbose_name='Nội dung chương trình')),
                ('achievements', models.TextField(blank=True, verbose_name='Thành tích')),
                ('commitments', models.TextField(blank=True, verbose_name='Cam kết')),
                ('grade_levels', models.CharField(default='Tiểu học - THPT', max_length=100, verbose_name='Cấp học áp dụng')),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=50, verbose_name='Icon class')),
                ('color', models.CharField(default='primary', help_text='primary, accent, blue, green, purple, orange', max_length=20, verbose_name='Màu chủ đạo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_programs/', verbose_name='Ảnh đại diện')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hệ đào tạo',
                'verbose_name_plural': 'Các hệ đào tạo',
                'ordering': ['order'],
            },
        ),
    ]
