# Generated by Django 5.2.8 on 2025-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vn', models.CharField(max_length=200, verbose_name='Tên đầy đủ (Tiếng Việt)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Tên đầy đủ (Tiếng Anh)')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Tên viết tắt / Brand name')),
                ('address', models.TextField(verbose_name='Địa chỉ campus')),
                ('hotline', models.CharField(max_length=20, verbose_name='Số điện thoại hotline chính')),
                ('admissions_email', models.EmailField(max_length=254, verbose_name='Email tuyển sinh chính thức')),
                ('current_website', models.URLField(blank=True, verbose_name='Website hiện tại')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('zalo_url', models.URLField(blank=True, verbose_name='Zalo')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_info/', verbose_name='Logo trường')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school_info/', verbose_name='Favicon')),
                ('general_email', models.EmailField(blank=True, max_length=254, verbose_name='Email chung')),
                ('short_description', models.TextField(blank=True, verbose_name='Mô tả ngắn về trường')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông tin trường',
                'verbose_name_plural': 'Thông tin trường',
            },
        ),
        migrations.CreateModel(
            name='StudentLifePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề trang')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung chi tiết')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='student_life/', verbose_name='Ảnh banner')),
                ('activities', models.TextField(blank=True, help_text='Mỗi dòng là một hoạt động', verbose_name='Hoạt động')),
                ('clubs', models.TextField(blank=True, help_text='Mỗi dòng là một CLB', verbose_name='Câu lạc bộ')),
                ('events', models.TextField(blank=True, help_text='Mô tả các sự kiện', verbose_name='Sự kiện')),
                ('facilities', models.TextField(blank=True, verbose_name='Cơ sở vật chất')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang Đời sống học sinh',
                'verbose_name_plural': 'Trang Đời sống học sinh',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('tuyen_sinh', 'Tuyển sinh'), ('giao_duc', 'Giáo dục & Đào tạo'), ('truyen_thong', 'Truyền thông & Marketing'), ('ket_noi', 'Kết nối phụ huynh'), ('tin_tuc', 'Tin tức & Sự kiện'), ('tuyen_dung', 'Tuyển dụng'), ('khac', 'Khác')], max_length=20, verbose_name='Loại mục tiêu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('priority', models.IntegerField(default=0, help_text='Số càng lớn, ưu tiên càng cao', verbose_name='Độ ưu tiên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Mục tiêu website',
                'verbose_name_plural': 'Mục tiêu website',
                'ordering': ['-priority', 'goal_type'],
            },
        ),
    ]
