# Generated by Django 5.2.8 on 2025-12-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolinfo_studentlifepage_websitegoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='TA¦n c’\xad s\xa0¯Y')),
                ('address', models.TextField(verbose_name='Ž?\xa0¯<a ch\xa0¯%')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='S\xa0¯` Ž`i\xa0¯Øn tho\xa0§\xadi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='Google Maps embed URL')),
                ('is_primary', models.BooleanField(default=False, verbose_name='C’\xad s\xa0¯Y chA-nh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hi\xa0¯Ÿn th\xa0¯<')),
                ('order', models.IntegerField(default=0, verbose_name='Th\xa0¯c t\xa0¯ñ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.schoolinfo')),
            ],
            options={
                'verbose_name': 'C’\xad s\xa0¯Y',
                'verbose_name_plural': 'CA\xadc c’\xad s\xa0¯Y',
                'ordering': ['order', 'name'],
            },
        ),
    ]
