# Generated by Django 5.2.8 on 2026-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.CharField(help_text="VD: '98%', '7.5', 'HSK6', '50+'", max_length=50, verbose_name='Giá trị thống kê')),
                ('stat_label', models.CharField(help_text="VD: 'Tỷ lệ đậu Đại học'", max_length=100, verbose_name='Nhãn thống kê')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề thành tích')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('icon', models.CharField(default='fas fa-trophy', help_text='FontAwesome class', max_length=50, verbose_name='Icon')),
                ('tags', models.CharField(blank=True, help_text="Các tag cách nhau bởi dấu phẩy, VD: 'ASMO, Kangaroo, SASMO'", max_length=300, verbose_name='Tags')),
                ('category', models.CharField(choices=[('academic', 'Học thuật'), ('competition', 'Cuộc thi'), ('language', 'Ngôn ngữ'), ('scholarship', 'Học bổng'), ('sports', 'Thể thao'), ('arts', 'Nghệ thuật'), ('technology', 'Công nghệ'), ('other', 'Khác')], default='academic', max_length=20, verbose_name='Danh mục')),
                ('color', models.CharField(choices=[('red', 'Đỏ'), ('amber', 'Vàng cam'), ('green', 'Xanh lá'), ('blue', 'Xanh dương'), ('purple', 'Tím'), ('pink', 'Hồng')], default='red', max_length=20, verbose_name='Màu chủ đạo')),
                ('is_stat', models.BooleanField(default=False, help_text='Tick để hiển thị trong phần số liệu thống kê', verbose_name='Hiển thị dạng thống kê')),
                ('is_card', models.BooleanField(default=True, help_text='Tick để hiển thị trong phần achievement cards', verbose_name='Hiển thị dạng card')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thành tích',
                'verbose_name_plural': 'Thành tích nổi bật',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FounderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=100, verbose_name='Tên người sáng lập')),
                ('founder_title', models.CharField(max_length=200, verbose_name='Chức danh')),
                ('founder_photo', models.ImageField(blank=True, help_text='Ảnh tròn, tỉ lệ 1:1', null=True, upload_to='founder/', verbose_name='Ảnh chân dung')),
                ('main_quote', models.TextField(help_text='Câu quote ngắn hiển thị trên trang chủ', verbose_name='Trích dẫn chính')),
                ('greeting', models.CharField(blank=True, default='Ba mẹ và các con học sinh thân mến,', max_length=200, verbose_name='Lời chào')),
                ('full_message', models.TextField(verbose_name='Thông điệp đầy đủ')),
                ('closing_message', models.TextField(blank=True, verbose_name='Lời kết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông điệp người sáng lập',
                'verbose_name_plural': 'Thông điệp người sáng lập',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chính')),
                ('title_highlight', models.CharField(blank=True, max_length=200, verbose_name='Phần highlight của tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề phụ')),
                ('slogan', models.CharField(blank=True, default='Giáo dục con tim – Kiến tạo giá trị sống', max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('badge_text', models.CharField(blank=True, help_text="VD: 'Đang mở đăng ký', 'Chương trình đặc biệt'", max_length=100, verbose_name='Badge text')),
                ('badge_icon', models.CharField(blank=True, help_text="FontAwesome class, VD: 'fas fa-calendar-check'", max_length=50, verbose_name='Badge icon')),
                ('slide_type', models.CharField(choices=[('welcome', 'Welcome/Giới thiệu'), ('admissions', 'Tuyển sinh'), ('program', 'Chương trình học'), ('activities', 'Hoạt động'), ('event', 'Sự kiện'), ('other', 'Khác')], default='welcome', max_length=20, verbose_name='Loại slide')),
                ('cta_primary_text', models.CharField(blank=True, max_length=100, verbose_name='Nút chính - Text')),
                ('cta_primary_url', models.CharField(blank=True, max_length=200, verbose_name='Nút chính - URL')),
                ('cta_primary_icon', models.CharField(blank=True, help_text="VD: 'fas fa-arrow-right'", max_length=50, verbose_name='Nút chính - Icon')),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100, verbose_name='Nút phụ - Text')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200, verbose_name='Nút phụ - URL')),
                ('image', models.ImageField(help_text='Kích thước khuyến nghị: 1920x1080px', upload_to='hero/', verbose_name='Ảnh nền')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(help_text="VD: 'PHHS Đức Minh'", max_length=100, verbose_name='Tên phụ huynh')),
                ('student_class', models.CharField(help_text="VD: '2S2', '12A5'", max_length=50, verbose_name='Lớp học sinh')),
                ('photo', models.ImageField(help_text='Ảnh khổ dọc, tỉ lệ 2:3', upload_to='testimonials/', verbose_name='Ảnh phụ huynh')),
                ('title', models.CharField(help_text="VD: 'Phụ huynh chia sẻ về hành trình học tập'", max_length=200, verbose_name='Tiêu đề chia sẻ')),
                ('short_quote', models.TextField(help_text='Hiển thị trên carousel', verbose_name='Trích dẫn ngắn')),
                ('full_content', models.TextField(help_text='Hiển thị trong modal', verbose_name='Nội dung đầy đủ')),
                ('achievement', models.CharField(blank=True, help_text="VD: 'HSK6 năm lớp 11', 'Học bổng toàn phần ĐH Ngôn ngữ Bắc Kinh'", max_length=200, verbose_name='Thành tích con')),
                ('video_url', models.URLField(blank=True, help_text='Google Drive hoặc YouTube embed URL', verbose_name='URL Video')),
                ('has_video', models.BooleanField(default=False, verbose_name='Có video')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chia sẻ phụ huynh',
                'verbose_name_plural': 'Chia sẻ phụ huynh',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đối tác')),
                ('logo', models.ImageField(help_text='Kích thước khuyến nghị: 200x100px, nền trong suốt', upload_to='partners/', verbose_name='Logo')),
                ('url', models.URLField(verbose_name='Website đối tác')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('partner_type', models.CharField(choices=[('education', 'Đối tác giáo dục'), ('training', 'Đối tác đào tạo'), ('technology', 'Đối tác công nghệ'), ('international', 'Đối tác quốc tế'), ('sponsor', 'Nhà tài trợ'), ('other', 'Khác')], default='education', max_length=20, verbose_name='Loại đối tác')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('show_in_marquee', models.BooleanField(default=True, verbose_name='Hiển thị trên marquee trang chủ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác hợp tác',
                'ordering': ['order', 'name'],
            },
        ),
    ]
