# Generated by Django 5.2.8 on 2026-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_achievement_foundermessage_heroslide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Tên học sinh')),
                ('student_class', models.CharField(help_text="VD: '12A5', '9S1', 'Khóa 2022-2025'", max_length=50, verbose_name='Lớp')),
                ('photo', models.ImageField(help_text='Ảnh chân dung hoặc ảnh nhận giải, tỉ lệ 4:3 hoặc 16:9', upload_to='student_spotlight/', verbose_name='Ảnh học sinh')),
                ('title', models.CharField(help_text="VD: 'Huy chương Vàng ASMO 2025'", max_length=200, verbose_name='Tiêu đề thành tích')),
                ('achievement', models.TextField(help_text='Chi tiết về thành tích đạt được', verbose_name='Mô tả thành tích')),
                ('category', models.CharField(choices=[('academic', 'Học thuật'), ('competition', 'Cuộc thi'), ('language', 'Ngôn ngữ'), ('scholarship', 'Học bổng'), ('sports', 'Thể thao'), ('arts', 'Nghệ thuật'), ('leadership', 'Lãnh đạo'), ('other', 'Khác')], default='academic', max_length=20, verbose_name='Danh mục')),
                ('quote', models.TextField(blank=True, help_text='Câu nói/chia sẻ của học sinh (tùy chọn)', verbose_name='Trích dẫn từ học sinh')),
                ('tags', models.CharField(blank=True, help_text="VD: 'ASMO, Huy chương Vàng, Toán học'. Cách nhau bởi dấu phẩy", max_length=300, verbose_name='Tags thành tích')),
                ('article_url', models.URLField(blank=True, help_text='Link đến bài viết đầy đủ (nếu có)', verbose_name='Link bài viết chi tiết')),
                ('is_featured', models.BooleanField(default=False, help_text='Tick để hiển thị trên carousel trang chủ', verbose_name='Nổi bật trên trang chủ')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gương mặt học sinh',
                'verbose_name_plural': 'Gương mặt học sinh nổi bật',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
