# Generated by Django 5.2.8 on 2026-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentspotlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Cơ sở', 'verbose_name_plural': 'Các cơ sở'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Cơ sở chính'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên cơ sở'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
