# Generated by Django 5.2.8 on 2026-01-16 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_campus_options_alter_campus_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Training Program Group',
                'verbose_name_plural': 'Training Program Groups',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.trainingprogramgroup'),
        ),
    ]
