# Generated by Django 5.2.8 on 2026-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trainingprogramgroup_trainingprogram_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('classroom', 'Phòng học'), ('lab', 'Phòng lab'), ('utility', 'Tiện ích')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps embed iframe hoặc URL.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cơ sở vật chất',
                'verbose_name_plural': 'Cơ sở vật chất',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text="FontAwesome class (e.g., 'fas fa-heart')", max_length=100)),
                ('short_description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trụ cột giáo dục',
                'verbose_name_plural': 'Trụ cột giáo dục',
                'ordering': ['order', 'title'],
            },
        ),
    ]
