# Generated by Django 5.2.8 on 2026-01-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_home_award_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspotlight',
            name='student_class',
            field=models.CharField(blank=True, help_text="VD: '12A5', '9S1', 'Khóa 2022-2025'", max_length=50, null=True, verbose_name='Lớp'),
        ),
    ]
