# Generated by Django 5.2.8 on 2026-01-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_allow_null_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('youtube_url', models.URLField(help_text='VD: https://youtu.be/Q6C89WUHoNg', verbose_name='Link YouTube')),
                ('thumbnail', models.ImageField(blank=True, help_text='Nếu để trống sẽ tự động lấy từ YouTube', null=True, upload_to='podcasts/', verbose_name='Ảnh thumbnail')),
                ('host_name', models.CharField(blank=True, max_length=100, verbose_name='Người dẫn')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Khách mời')),
                ('duration', models.CharField(blank=True, help_text="VD: '15:30', '1:02:45'", max_length=20, verbose_name='Thời lượng')),
                ('episode_number', models.PositiveIntegerField(default=1, verbose_name='Số tập')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Tiếng nói MISERs - Podcasts',
                'ordering': ['-episode_number', '-published_date', 'order'],
            },
        ),
    ]
