# Generated by Django 5.2.8 on 2026-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_podcast_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['group', 'order'], 'verbose_name': 'Giá trị cốt lõi', 'verbose_name_plural': 'Giá trị cốt lõi'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Năm đạt được'),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='group',
            field=models.CharField(choices=[('grace', 'GRACE (Giá trị cốt lõi)'), ('5xin', '5 Xin'), ('5biet', '5 Biết'), ('5khong', '5 Không'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nhóm giá trị'),
        ),
    ]
