# Generated by Django 5.2.8 on 2026-02-08 10:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_program_overview_local_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='youtube_url',
            field=models.URLField(help_text='VD: https://youtu.be/Q6C89WUHoNg', validators=[core.validators.validate_youtube_url], verbose_name='Link YouTube'),
        ),
    ]
