# Generated by Django 5.2.8 on 2026-02-15 10:42

from pathlib import Path

from django.db import migrations, models


PROGRAM_YEAR = "2026-2027"
SOURCE_DOC = "tmp_mis_program_2026_2027"
CONTENT_VERSION = "2026.1"
BLOCK_START = "{% block lowfi_body %}"
BLOCK_END = "{% endblock %}"

URL_REPLACEMENTS = {
    "{% url 'core:mis_lowfi_page' page_key='preparation' %}": "/prototype/mis/preparation/",
    "{% url 'core:mis_lowfi_page' page_key='primary' %}": "/prototype/mis/primary/",
    "{% url 'core:mis_lowfi_page' page_key='thcs' %}": "/prototype/mis/thcs/",
    "{% url 'core:mis_lowfi_page' page_key='thpt' %}": "/prototype/mis/thpt/",
    "{% url 'core:mis_lowfi_page' page_key='edtech' %}": "/prototype/mis/edtech/",
    "{% url 'core:mis_lowfi_page' page_key='parent-portal' %}": "/prototype/mis/parent-portal/",
    "{% url 'contact:contact' %}": "/contact/",
}

PAGE_TEMPLATE_MAP = [
    ("home", "Trang chủ", "MIS - Trang chủ", "mis_home.html", 0),
    ("preparation", "Mầm non", "MIS - Mầm non & Tiền tiểu học", "mis_preparation.html", 1),
    ("primary", "Tiểu học", "MIS - Cấp Tiểu học", "mis_primary.html", 2),
    ("thcs", "THCS", "MIS - Cấp THCS", "mis_thcs.html", 3),
    ("thpt", "THPT", "MIS - Cấp THPT", "mis_thpt.html", 4),
    ("edtech", "EdTech", "MIS - Hệ sinh thái EdTech", "mis_edtech.html", 5),
    ("parent-portal", "Phụ huynh", "MIS - Cổng phụ huynh", "mis_parent_portal.html", 6),
]


def _extract_lowfi_body(template_path):
    if not template_path.exists():
        return ""
    content = template_path.read_text(encoding="utf-8")
    start = content.find(BLOCK_START)
    end = content.rfind(BLOCK_END)
    if start == -1 or end == -1 or end <= start:
        return ""

    body = content[start + len(BLOCK_START):end].strip()
    for raw, resolved in URL_REPLACEMENTS.items():
        body = body.replace(raw, resolved)
    return body


def seed_mis_lowfi_content(apps, schema_editor):
    site_model = apps.get_model("core", "MISPrototypeSiteContent")
    page_model = apps.get_model("core", "MISPrototypePage")

    site_model.objects.update_or_create(
        year=PROGRAM_YEAR,
        defaults={
            "title": "Hệ thống giáo dục MIS 2026-2027",
            "badge": "AI-integrated | Creative Economy | Global Citizen",
            "lead": (
                "Chuyển dịch từ nền kinh tế tri thức sang nền kinh tế sáng tạo: học sinh trở thành nhà lãnh đạo công nghệ, "
                "giáo viên là kiến trúc sư tri thức và kỹ sư tâm hồn."
            ),
            "meta_description": "Prototype MIS 2026-2027: giáo dục AI-tích hợp, tư duy sáng tạo và phát triển toàn diện.",
            "cta_primary_label": "Đăng ký tư vấn",
            "cta_primary_href": "/admissions/",
            "cta_primary_icon": "fas fa-calendar-check",
            "cta_secondary_label": "Tham quan trường",
            "cta_secondary_href": "/contact/",
            "cta_secondary_icon": "fas fa-map-marked-alt",
            "metrics": [
                {"value": "7", "label": "Trang cốt lõi"},
                {"value": PROGRAM_YEAR, "label": "Năm học"},
                {"value": "AI + Nhân bản", "label": "Mô hình giáo dục"},
                {"value": "Toàn cầu", "label": "Công dân thế hệ mới"},
            ],
            "source_doc": SOURCE_DOC,
            "version": CONTENT_VERSION,
            "is_active": True,
        },
    )

    base_dir = Path(__file__).resolve().parents[2]
    template_dir = base_dir / "templates" / "core" / "lowfi"

    for page_key, nav_label, browser_title, template_name, order in PAGE_TEMPLATE_MAP:
        body_html = _extract_lowfi_body(template_dir / template_name)
        page_model.objects.update_or_create(
            year=PROGRAM_YEAR,
            page_key=page_key,
            defaults={
                "nav_label": nav_label,
                "title": browser_title.replace("MIS - ", ""),
                "browser_title": browser_title,
                "meta_description": browser_title,
                "body_html": body_html,
                "blocks": [],
                "order": order,
                "source_doc": SOURCE_DOC,
                "version": CONTENT_VERSION,
                "is_active": True,
            },
        )


def rollback_mis_lowfi_content(apps, schema_editor):
    site_model = apps.get_model("core", "MISPrototypeSiteContent")
    page_model = apps.get_model("core", "MISPrototypePage")
    page_model.objects.filter(year=PROGRAM_YEAR).delete()
    site_model.objects.filter(year=PROGRAM_YEAR).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_podcast_youtube_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MISPrototypeSiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.CharField(db_index=True, max_length=9, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("badge", models.CharField(blank=True, max_length=255)),
                ("lead", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_href", models.CharField(blank=True, max_length=255)),
                ("cta_primary_icon", models.CharField(blank=True, max_length=100)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_href", models.CharField(blank=True, max_length=255)),
                ("cta_secondary_icon", models.CharField(blank=True, max_length=100)),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("source_doc", models.CharField(default="tmp_mis_program_2026_2027", max_length=255)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="2026.1", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MIS Prototype Site Content",
                "verbose_name_plural": "MIS Prototype Site Content",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="MISPrototypePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_key", models.SlugField(max_length=50)),
                ("year", models.CharField(db_index=True, max_length=9)),
                ("nav_label", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("browser_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("source_doc", models.CharField(default="tmp_mis_program_2026_2027", max_length=255)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="2026.1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MIS Prototype Page",
                "verbose_name_plural": "MIS Prototype Pages",
                "ordering": ["year", "order", "page_key"],
                "constraints": [
                    models.UniqueConstraint(fields=("year", "page_key"), name="mis_prototype_unique_year_key")
                ],
            },
        ),
        migrations.RunPython(seed_mis_lowfi_content, rollback_mis_lowfi_content),
    ]
