# Generated by Django 5.2.8 on 2026-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_misprototypesitecontent_misprototypepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='system_group',
            field=models.CharField(choices=[('steam', 'Hệ STEAM Chuẩn / CLC'), ('math_tech', 'Hệ Tài năng Toán – Công nghệ mới'), ('language', 'Hệ Tài năng Ngôn ngữ')], default='steam', help_text='Nhóm theo cấu trúc 3 hệ trong tài liệu chính thức', max_length=20, verbose_name='Nhóm hệ đào tạo (docx 2026-2027)'),
        ),
    ]
