# Generated by Django 5.2.8 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_system_group_to_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=9, unique=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('source_doc', models.CharField(default='program_content_json_import', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Content Source',
                'verbose_name_plural': 'Program Content Sources',
                'ordering': ['-year'],
            },
        ),
    ]
