# Generated by Django 5.2.8 on 2026-03-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_program_content_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Kích thước khuyến nghị: 200x100px, nền trong suốt', null=True, upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('education', 'Đối tác giáo dục'), ('training', 'Đối tác đào tạo'), ('technology', 'Đối tác công nghệ'), ('language', 'Đối tác ngoại ngữ'), ('community', 'Đối tác cộng đồng'), ('international', 'Đối tác quốc tế'), ('sponsor', 'Nhà tài trợ'), ('other', 'Khác')], default='education', max_length=20, verbose_name='Loại đối tác'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Website đối tác'),
        ),
    ]
