# Generated by Django 5.2.8 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_update_partner_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for achievement card', max_length=255, null=True, upload_to='achiement/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='corevaluespage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='core_values/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='foundermessage',
            name='founder_photo',
            field=models.ImageField(blank=True, help_text='Ảnh tròn, tỉ lệ 1:1', max_length=255, null=True, upload_to='founder/', verbose_name='Ảnh chân dung'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Kích thước khuyến nghị: 1920x1080px', max_length=255, upload_to='hero/', verbose_name='Ảnh nền'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='mis/2026/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_jpeg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='mis/2026/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_webp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='mis/2026/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='mis/2026/'),
        ),
        migrations.AlterField(
            model_name='parenttestimonial',
            name='photo',
            field=models.ImageField(help_text='Ảnh khổ dọc, tỉ lệ 2:3', max_length=255, upload_to='testimonials/', verbose_name='Ảnh phụ huynh'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Kích thước khuyến nghị: 200x100px, nền trong suốt', max_length=255, null=True, upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Nếu để trống sẽ tự động lấy từ YouTube', max_length=255, null=True, upload_to='podcasts/', verbose_name='Ảnh thumbnail'),
        ),
        migrations.AlterField(
            model_name='programoverviewimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='program_overview/pages/'),
        ),
        migrations.AlterField(
            model_name='programoverviewpage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='program_overview/hero/'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='favicon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='school_info/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='school_info/', verbose_name='Logo trường'),
        ),
        migrations.AlterField(
            model_name='studentlifepage',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='student_life/', verbose_name='Ảnh banner'),
        ),
        migrations.AlterField(
            model_name='studentspotlight',
            name='photo',
            field=models.ImageField(help_text='Ảnh chân dung hoặc ảnh nhận giải, tỉ lệ 4:3 hoặc 16:9', max_length=255, upload_to='student_spotlight/', verbose_name='Ảnh học sinh'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='training_programs/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='partner_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='training_programs/partners/', verbose_name='Logo đối tác'),
        ),
    ]
