# Generated by Django 5.2.8 on 2026-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_achievement_image_alter_corevaluespage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='VD: TKB Mới Nhất 30/04/2026', max_length=200, verbose_name='Tên Phiên bản TKB')),
                ('zip_file', models.FileField(help_text='Nén toàn bộ file TKB thành file .zip rồi tải lên đây.', upload_to='tkb_uploads/', verbose_name='File ZIP Thời khóa biểu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng (Giải nén)')),
            ],
            options={
                'verbose_name': 'Cập nhật Thời khóa biểu',
                'verbose_name_plural': 'Cập nhật Thời khóa biểu (ZIP)',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
