# Generated by Django 5.2.8 on 2026-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type', models.CharField(choices=[('extracurricular', 'Ngoại khóa'), ('summer_camp', 'Trại hè'), ('international', 'Quốc tế')], default='extracurricular', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hoạt động',
                'verbose_name_plural': 'Hoạt động ngoại khóa',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
