# Generated by Django 5.2.8 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
