# Generated by Django 5.2.8 on 2026-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(choices=[('teacher', 'Giáo viên'), ('admin', 'Quản trị'), ('ai', 'AI / Công nghệ')], default='teacher', max_length=20)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, help_text='Danh sách ngôn ngữ, phân tách bằng dấu phẩy.', max_length=200)),
                ('specialties', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Đội ngũ nhân sự',
                'ordering': ['role', 'name'],
            },
        ),
    ]
