# Generated by Django 5.2.8 on 2025-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên phụ huynh')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('grade_level', models.CharField(choices=[('mam_non', 'Mầm non - Tiền tiểu học'), ('tieu_hoc', 'Tiểu học (Lớp 1-5)'), ('thcs', 'THCS (Lớp 6-9)'), ('thpt', 'THPT (Lớp 10-12)')], max_length=20, verbose_name='Cấp học quan tâm')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung cần tư vấn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Đã liên hệ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
            ],
            options={
                'verbose_name': 'Đăng ký tư vấn',
                'verbose_name_plural': 'Đăng ký tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
