# Generated by Django 5.2.8 on 2026-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_add_interest_fields_to_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', 'Chưa chọn'), ('mam_non', 'Mầm non - Tiền tiểu học'), ('tieu_hoc', 'Tiểu học (Lớp 1-5)'), ('thcs', 'THCS (Lớp 6-9)'), ('thpt', 'THPT (Lớp 10-12)')], default='', max_length=20, verbose_name='Cấp học quan tâm'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='interest_admission_process',
            field=models.BooleanField(default=False, verbose_name='Tư vấn quy trình tuyển sinh'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='interest_curriculum',
            field=models.BooleanField(default=False, verbose_name='Tư vấn chương trình học'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='interest_visit',
            field=models.BooleanField(default=False, verbose_name='Hẹn lịch tham quan trường'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
