# Generated by Django 5.2.8 on 2025-12-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('mam_non', 'Mầm non - Tiền tiểu học'), ('tieu_hoc', 'Tiểu học'), ('thcs', 'Trung học cơ sở'), ('thpt', 'Trung học phổ thông')], max_length=20, unique=True, verbose_name='Cấp học')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('school_year', models.CharField(default='2025-2026', max_length=20, verbose_name='Năm học')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Giới thiệu chung')),
                ('age_range', models.CharField(blank=True, help_text='VD: 2-5 tuổi', max_length=100, verbose_name='Độ tuổi')),
                ('requirements', models.TextField(verbose_name='Điều kiện tuyển sinh')),
                ('tuition_info', models.TextField(verbose_name='Thông tin học phí')),
                ('process', models.TextField(verbose_name='Quy trình đăng ký')),
                ('benefits', models.TextField(blank=True, verbose_name='Ưu đãi - Học bổng')),
                ('facilities', models.TextField(blank=True, verbose_name='Cơ sở vật chất')),
                ('curriculum', models.TextField(blank=True, verbose_name='Chương trình học')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Hạn đăng ký')),
                ('image', models.ImageField(blank=True, upload_to='admissions/', verbose_name='Ảnh đại diện')),
                ('banner_image', models.ImageField(blank=True, upload_to='admissions/banners/', verbose_name='Ảnh banner')),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=100, verbose_name='Icon class')),
                ('color', models.CharField(default='red', help_text='VD: red, blue, green, purple', max_length=50, verbose_name='Màu chủ đạo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang tuyển sinh')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông tin tuyển sinh',
                'verbose_name_plural': 'Thông tin tuyển sinh',
                'ordering': ['order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('icon', models.CharField(default='fas fa-check', max_length=100, verbose_name='Icon class')),
                ('order', models.IntegerField(default=0)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='admissions.admissioninfo')),
            ],
            options={
                'verbose_name': 'Điểm nổi bật',
                'verbose_name_plural': 'Điểm nổi bật',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Họ tên phụ huynh')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('student_name', models.CharField(max_length=100, verbose_name='Họ tên học sinh')),
                ('student_dob', models.DateField(verbose_name='Ngày sinh')),
                ('student_gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('current_school', models.CharField(blank=True, max_length=200, verbose_name='Trường đang học')),
                ('current_grade', models.CharField(blank=True, max_length=50, verbose_name='Lớp hiện tại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(default='Hà Nội', max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('how_did_you_know', models.CharField(blank=True, max_length=200, verbose_name='Biết đến MIS qua')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('contacted', 'Đã liên hệ'), ('scheduled', 'Đã hẹn lịch'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='admissions.admissioninfo', verbose_name='Cấp học đăng ký')),
            ],
            options={
                'verbose_name': 'Đơn đăng ký tuyển sinh',
                'verbose_name_plural': 'Đơn đăng ký tuyển sinh',
                'ordering': ['-created_at'],
            },
        ),
    ]
