# Generated by Django 5.2.8 on 2026-01-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tài liệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('document_type', models.CharField(choices=[('form', 'Đơn đăng ký'), ('guide', 'Hướng dẫn tuyển sinh'), ('tuition', 'Bảng học phí'), ('curriculum', 'Chương trình học'), ('scholarship', 'Thông tin học bổng'), ('calendar', 'Lịch tuyển sinh'), ('other', 'Tài liệu khác')], default='other', max_length=20, verbose_name='Loại tài liệu')),
                ('file', models.FileField(upload_to='admissions/documents/%Y/', verbose_name='File tài liệu')),
                ('file_size', models.CharField(blank=True, max_length=20, verbose_name='Kích thước file')),
                ('school_year', models.CharField(default='2025-2026', max_length=20, verbose_name='Năm học')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Số lượt tải')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissioninfo', verbose_name='Cấp học')),
            ],
            options={
                'verbose_name': 'Tài liệu tuyển sinh',
                'verbose_name_plural': 'Tài liệu tuyển sinh',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
