# Generated by Django 5.2.8 on 2026-02-08 10:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_add_admission_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='file',
            field=models.FileField(upload_to='admissions/documents/%Y/', validators=[core.validators.validate_upload_extension, core.validators.validate_upload_file_size], verbose_name='File tài liệu'),
        ),
    ]
