# Generated by Django 5.2.8 on 2026-02-13 15:10

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_admissiondocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='school_year',
            field=models.CharField(default=admissions.models.get_default_school_year, max_length=20, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='school_year',
            field=models.CharField(default=admissions.models.get_default_school_year, max_length=20, verbose_name='Năm học'),
        ),
    ]
