# Generated by Django 5.2.8 on 2026-03-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admissiondocument_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionregistration',
            name='interest_admission_process',
            field=models.BooleanField(default=False, verbose_name='Tư vấn quy trình tuyển sinh'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='interest_curriculum',
            field=models.BooleanField(default=False, verbose_name='Tư vấn chương trình học'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='interest_visit',
            field=models.BooleanField(default=False, verbose_name='Hẹn lịch tham quan trường'),
        ),
    ]
