# Generated by Django 5.2.8 on 2026-03-26 06:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_add_interest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='file',
            field=models.FileField(max_length=255, upload_to='admissions/documents/%Y/', validators=[core.validators.validate_upload_extension, core.validators.validate_upload_file_size], verbose_name='File tài liệu'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='admissions/banners/', verbose_name='Ảnh banner'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='admissions/', verbose_name='Ảnh đại diện'),
        ),
    ]
