# Generated by Django 5.2.8 on 2026-04-08 11:49

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_admissiondocument_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_grade', models.CharField(choices=[('mam_non', 'Mầm non'), ('tien_tieu_hoc', 'Tiền tiểu học'), ('lop_1', 'Lớp 1'), ('lop_2', 'Lớp 2'), ('lop_3', 'Lớp 3'), ('lop_4', 'Lớp 4'), ('lop_5', 'Lớp 5'), ('lop_6', 'Lớp 6'), ('lop_7', 'Lớp 7'), ('lop_8', 'Lớp 8'), ('lop_9', 'Lớp 9'), ('lop_10', 'Lớp 10'), ('lop_11', 'Lớp 11'), ('lop_12', 'Lớp 12')], max_length=30, verbose_name='Tìm hiểu lớp')),
                ('training_program', models.CharField(blank=True, choices=[('steam_chuan', 'STEAM chuẩn'), ('steam_clc', 'STEAM CLC'), ('tai_nang_toan_cn', 'Tài năng Toán - Công nghệ mới'), ('tai_nang_nn_en_cn', 'Tài năng ngôn ngữ Tiếng Anh & Tiếng Trung'), ('clc_cong_nghe', 'CLC Công nghệ (Bổ sung lớp 2-9)'), ('tai_nang_nn', 'Tài năng ngôn ngữ (Bổ sung lớp 3-9)'), ('tai_nang_toan_a', 'Tài năng Toán - Ban A (Bổ sung lớp 7 & 11)'), ('clc_ban_a', 'CLC - Ban A (Bổ sung Lớp 11 & 12)'), ('clc_ban_d', 'CLC - Ban D (Bổ sung Lớp 11 & 12)'), ('tai_nang_nn_d', 'Tài năng ngôn ngữ - Ban D (Bổ sung Lớp 11 & 12)')], max_length=30, verbose_name='Hệ đào tạo')),
                ('details', models.TextField(help_text='Liệt kê thông tin mà Phụ huynh mong muốn được nhận', verbose_name='Chi tiết')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Họ tên Phụ huynh')),
                ('phone', models.CharField(max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('contacted', 'Đã liên hệ'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn tư vấn tuyển sinh',
                'verbose_name_plural': 'Đơn tư vấn tuyển sinh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='achievements',
            field=models.TextField(blank=True, help_text='Ghi rõ cấp: Phường/Xã, Quận/Thành phố, Quốc gia, Quốc tế', verbose_name='Thành tích đạt được'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='admission_method',
            field=models.CharField(blank=True, choices=[('xet_tuyen_thang', 'Xét tuyển thẳng'), ('kiem_tra_dau_vao', 'Kiểm tra đầu vào'), ('thi_hoc_bong', 'Thi học bổng')], max_length=30, verbose_name='Phương thức tuyển sinh'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='best_subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Môn học tốt nhất'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='contact_relationship',
            field=models.CharField(blank=True, choices=[('bo', 'Bố'), ('me', 'Mẹ'), ('ong_ba', 'Ông/Bà'), ('anh_chi', 'Anh/Chị'), ('khac', 'Khác')], max_length=20, verbose_name='Quan hệ với học sinh'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='favorite_subjects',
            field=models.TextField(blank=True, help_text='VD: Toán, Tiếng Anh, Khoa học', verbose_name='Các môn học yêu thích'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='referrer',
            field=models.CharField(blank=True, help_text='Từ đâu anh/chị biết đến trường để đăng ký', max_length=200, verbose_name='Người giới thiệu'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='register_boarding',
            field=models.BooleanField(default=False, verbose_name='Đăng ký nội trú'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='register_dayboarding',
            field=models.BooleanField(default=False, verbose_name='Đăng ký bán trú'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='register_shuttle',
            field=models.BooleanField(default=False, verbose_name='Đăng ký xe đưa đón'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='registration_school_year',
            field=models.CharField(choices=[('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=admissions.models.get_default_school_year, max_length=20, verbose_name='Năm học đăng ký'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='study_abroad_plan',
            field=models.BooleanField(default=False, verbose_name='Dự định du học'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='talent_subjects',
            field=models.TextField(blank=True, help_text='VD: Piano, Bơi lội, Vẽ, Robotics', verbose_name='Môn năng khiếu đang học'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='target_grade',
            field=models.CharField(blank=True, choices=[('mam_non', 'Mầm non'), ('tien_tieu_hoc', 'Tiền tiểu học'), ('lop_1', 'Lớp 1'), ('lop_2', 'Lớp 2'), ('lop_3', 'Lớp 3'), ('lop_4', 'Lớp 4'), ('lop_5', 'Lớp 5'), ('lop_6', 'Lớp 6'), ('lop_7', 'Lớp 7'), ('lop_8', 'Lớp 8'), ('lop_9', 'Lớp 9'), ('lop_10', 'Lớp 10'), ('lop_11', 'Lớp 11'), ('lop_12', 'Lớp 12')], max_length=30, verbose_name='Khối lớp dự tuyển'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='training_program',
            field=models.CharField(blank=True, choices=[('steam_chuan', 'STEAM chuẩn'), ('steam_clc', 'STEAM CLC'), ('tai_nang_toan_cn', 'Tài năng Toán - Công nghệ mới'), ('tai_nang_nn_en_cn', 'Tài năng ngôn ngữ Tiếng Anh & Tiếng Trung'), ('clc_cong_nghe', 'CLC Công nghệ (Bổ sung lớp 2-9)'), ('tai_nang_nn', 'Tài năng ngôn ngữ (Bổ sung lớp 3-9)'), ('tai_nang_toan_a', 'Tài năng Toán - Ban A (Bổ sung lớp 7 & 11)'), ('clc_ban_a', 'CLC - Ban A (Bổ sung Lớp 11 & 12)'), ('clc_ban_d', 'CLC - Ban D (Bổ sung Lớp 11 & 12)'), ('tai_nang_nn_d', 'Tài năng ngôn ngữ - Ban D (Bổ sung Lớp 11 & 12)')], max_length=30, verbose_name='Hệ đào tạo'),
        ),
        migrations.AddField(
            model_name='admissionregistration',
            name='transcript_file',
            field=models.FileField(blank=True, help_text='Học bạ / Phiếu điểm HK1, HK2 — scan PDF hoặc ảnh, tối đa 2 MB', null=True, upload_to='admissions/transcripts/%Y/%m/', validators=[admissions.models.validate_transcript_extension, admissions.models.validate_transcript_file_size], verbose_name='Minh chứng xét tuyển thẳng'),
        ),
        migrations.AlterField(
            model_name='admissionregistration',
            name='address',
            field=models.TextField(verbose_name='Nơi cư trú'),
        ),
        migrations.AlterField(
            model_name='admissionregistration',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên người liên hệ'),
        ),
        migrations.CreateModel(
            name='RegistrationSibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('current_school', models.CharField(max_length=200, verbose_name='Trường đang học')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='admissions.admissionregistration', verbose_name='Đơn đăng ký')),
            ],
            options={
                'verbose_name': 'Anh chị em ruột',
                'verbose_name_plural': 'Anh chị em ruột',
                'ordering': ['id'],
            },
        ),
    ]
