# Generated by Django 5.2.8 on 2025-12-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_type',
            field=models.CharField(choices=[('mission', 'Giới thiệu chung về MIS'), ('vision', 'Hệ thống giáo dục MIS'), ('principal', 'Thông điệp Tổng Giám đốc'), ('strengths', '8 điểm mạnh khác biệt'), ('strategy', 'Chiến lược phát triển'), ('structure', 'Cơ cấu tổ chức MIS'), ('culture', 'Quy định văn hóa MIS'), ('boarding', 'Môi trường nội trú'), ('happiness', 'Trường Văn minh – Hạnh phúc'), ('liberal', 'Giáo dục khai phóng'), ('math', 'Chương trình môn Toán'), ('literature', 'Chương trình môn Ngữ văn'), ('english', 'Chương trình Tiếng Anh'), ('chinese', 'Chương trình Tiếng Trung'), ('steam', 'Chương trình STEAM'), ('robotics', 'Chương trình Robotic'), ('lifeskills', 'Kỹ năng sống'), ('creative', 'Trải nghiệm sáng tạo'), ('whymis', 'Tại sao chọn MIS?')], max_length=30, unique=True),
        ),
    ]
