# Generated by Django 5.2.8 on 2025-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_type',
            field=models.CharField(choices=[('mission', 'Giới thiệu chung về MIS'), ('vision', 'Hệ thống giáo dục MIS'), ('principal', 'Thông điệp Tổng Giám đốc'), ('strengths', '8 điểm mạnh khác biệt'), ('strategy', 'Chiến lược phát triển'), ('structure', 'Cơ cấu tổ chức MIS'), ('culture', 'Quy định văn hóa MIS'), ('boarding', 'Môi trường nội trú'), ('happiness', 'Trường Văn minh – Hạnh phúc'), ('liberal', 'Giáo dục khai phóng'), ('overview_math', 'Tổng quan Chương trình môn Toán'), ('overview_literature', 'Tổng quan Chương trình môn Ngữ văn'), ('overview_english', 'Tổng quan Chương trình Tiếng Anh'), ('overview_chinese', 'Tổng quan Chương trình Tiếng Trung'), ('tnst', 'Chương trình Trải nghiệm sáng tạo (TNST)'), ('steam', 'Chương trình STEAM với Công nghệ sáng tạo'), ('robotics', 'Chương trình Robotic'), ('lifeskills', 'Chương trình Kỹ năng sống'), ('creative_movement', 'Chương trình Tâm vấn động'), ('schedule_2025', 'Khung Kế hoạch năm học 2025-2026'), ('schedule_hd', 'Khung Kế hoạch HĐ phòng tràào năm học 2025-2026'), ('whymis', 'Tại sao chọn MIS?')], max_length=30, unique=True),
        ),
    ]
