# Generated by Django 5.2.8 on 2025-12-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, help_text='Legacy content field - use sections for new pages'),
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of section on page')),
                ('layout', models.CharField(choices=[('hero', 'Hero Section'), ('text_left', 'Text Left, Image Right'), ('text_right', 'Text Right, Image Left'), ('full_text', 'Full Width Text'), ('stats', 'Statistics/Numbers'), ('quote', 'Quote/Testimonial'), ('cta', 'Call to Action'), ('features', 'Feature Grid')], default='full_text', max_length=20)),
                ('background', models.CharField(choices=[('white', 'White'), ('light', 'Light Grey'), ('navy', 'Navy Blue'), ('accent', 'Teal Accent'), ('gradient', 'Gradient')], default='white', max_length=20)),
                ('eyebrow', models.CharField(blank=True, help_text="Small text above title (e.g., 'WHY MIS')", max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/sections/')),
                ('highlight_text', models.CharField(blank=True, help_text='Text to highlight in accent color', max_length=100)),
                ('stat_number', models.CharField(blank=True, help_text="Large number for stats (e.g., '84%')", max_length=50)),
                ('stat_label', models.CharField(blank=True, help_text='Label below stat number', max_length=100)),
                ('cta_text', models.CharField(blank=True, help_text='Button text', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Button URL', max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['page', 'order'],
            },
        ),
    ]
