# Generated by Django 5.2.8 on 2026-01-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_aboutpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('page_type', models.SlugField(help_text='Slug or page_type used to map the PDF to a page', unique=True)),
                ('pdf_file', models.FileField(upload_to='about/pdfs/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/pdfs/hero/')),
            ],
            options={
                'verbose_name': 'About PDF Document',
                'verbose_name_plural': 'About PDF Documents',
            },
        ),
    ]
