# Generated by Django 5.2.8 on 2026-01-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_aboutpdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPdfPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/pdfs/pages/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='about.aboutpdfdocument')),
            ],
            options={
                'verbose_name': 'About PDF Page Image',
                'verbose_name_plural': 'About PDF Page Images',
                'ordering': ['order'],
            },
        ),
    ]
