# Generated by Django 5.2.8 on 2026-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_aboutpdfpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='kpi',
            field=models.TextField(blank=True, help_text='KPI items (one per line or JSON list)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='timeline',
            field=models.TextField(blank=True, help_text='Timeline items (one per line or JSON list)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='page_type',
            field=models.CharField(choices=[('mission', 'Về chúng tôi'), ('vision', 'Giá trị cốt lõi'), ('principal', 'Lịch sử hình thành'), ('strengths', '8 điểm mạnh khác biệt'), ('strategy', 'Chiến lược phát triển'), ('structure', 'Cơ cấu tổ chức MIS'), ('culture', 'Quy định văn hóa MIS'), ('boarding', 'Môi trường nội trú'), ('happiness', 'Trường Văn minh – Hạnh phúc'), ('liberal', 'Giáo dục khai phóng'), ('academics', 'Tổng quan Chương trình Giáo dục'), ('preschool', 'Chương trình Mầm non (3-6 tuổi)'), ('primary', 'Chương trình Tiểu học (Lớp 1-5)'), ('middle', 'Chương trình THCS (Lớp 6-9)'), ('high', 'Chương trình THPT (Lớp 10-12)'), ('overview_math', 'Tổng quan Chương trình môn Toán'), ('overview_literature', 'Tổng quan Chương trình môn Ngữ văn'), ('overview_english', 'Tổng quan Chương trình Tiếng Anh'), ('overview_chinese', 'Tổng quan Chương trình Tiếng Trung'), ('tnst', 'Chương trình Trải nghiệm sáng tạo (TNST)'), ('steam', 'Chương trình STEAM với Công nghệ sáng tạo'), ('robotics', 'Chương trình Robotic'), ('lifeskills', 'Chương trình Kỹ năng sống'), ('creative_movement', 'Chương trình Tâm vấn động'), ('schedule_2025', 'Khung Kế hoạch năm học 2025-2026'), ('schedule_hd', 'Khung Kế hoạch HĐ phòng tràào năm học 2025-2026'), ('whymis', 'Tại sao chọn MIS?'), ('strategy_2025_2028', 'Strategy 2025-2028'), ('vision_2033', 'Vision 2033')], max_length=30, unique=True),
        ),
    ]
