# Generated by Django 5.2.8 on 2026-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_aboutsection_kpi_aboutsection_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='about/feature_cards/'),
        ),
    ]
