# Generated by Django 5.2.8 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_alter_aboutpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpdfdocument',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/pdfs/hero/'),
        ),
        migrations.AlterField(
            model_name='aboutpdfdocument',
            name='page_type',
            field=models.SlugField(help_text='Slug or page_type used to map the PDF to a page', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='aboutpdfdocument',
            name='pdf_file',
            field=models.FileField(max_length=255, upload_to='about/pdfs/'),
        ),
        migrations.AlterField(
            model_name='aboutpdfpageimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='about/pdfs/pages/'),
        ),
        migrations.AlterField(
            model_name='aboutpdfpageimage',
            name='image_avif',
            field=models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='about/pdfs/pages/'),
        ),
        migrations.AlterField(
            model_name='aboutpdfpageimage',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='about/pdfs/pages/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_5',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='feature_image_6',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/feature_cards/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='about/sections/'),
        ),
    ]
