# Generated by Django 5.2.8 on 2026-01-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSRProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('impact_metrics', models.TextField(blank=True, help_text="Mỗi dòng là một chỉ số tác động, ví dụ: '2.000+ học sinh thụ hưởng'.")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dự án CSR',
                'verbose_name_plural': 'Dự án CSR',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CSRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='csr/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='csr.csrproject')),
            ],
            options={
                'verbose_name': 'Ảnh CSR',
                'verbose_name_plural': 'Ảnh CSR',
                'ordering': ['order'],
            },
        ),
    ]
