# Generated by Django 5.2.8 on 2026-03-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('period', models.CharField(help_text="Ví dụ: '2008 – 2017', 'Hàng năm', 'Mỗi dịp Tết'", max_length=50, verbose_name='Giai đoạn')),
                ('icon', models.CharField(default='fa-hand-holding-heart', help_text='Class icon FontAwesome, ví dụ: fa-moon, fa-gift', max_length=50, verbose_name='Icon FontAwesome')),
                ('short_description', models.TextField(help_text='Hiển thị trên card. 1-2 câu.', verbose_name='Mô tả ngắn')),
                ('full_description', models.TextField(help_text='Hiển thị trong modal chi tiết. Dùng <br> để xuống dòng.', verbose_name='Mô tả đầy đủ')),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh chính hiển thị trên card và header modal.', null=True, upload_to='csr/journey/covers/', verbose_name='Ảnh bìa')),
                ('tags', models.TextField(blank=True, help_text="Mỗi dòng là một tag, ví dụ: '10 năm đồng hành'", verbose_name='Tags')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('is_featured', models.BooleanField(default=False, help_text="3 chương trình nổi bật hiện trước, còn lại ẩn sau 'Xem thêm'.", verbose_name='Nổi bật')),
            ],
            options={
                'verbose_name': 'Chương trình Journey',
                'verbose_name_plural': 'Chương trình Journey',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='csr/journey/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='csr.journeyprogram')),
            ],
            options={
                'verbose_name': 'Ảnh Journey',
                'verbose_name_plural': 'Ảnh Journey',
                'ordering': ['order'],
            },
        ),
    ]
