# Generated by Django 5.2.8 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0002_journeyprogram_journeyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='csr/'),
        ),
        migrations.AlterField(
            model_name='csrproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='journeyimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='csr/journey/gallery/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='journeyprogram',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh chính hiển thị trên card và header modal.', max_length=255, null=True, upload_to='csr/journey/covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='journeyprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
